AWSTemplateFormatVersion: 2010-09-09
Description: "This CloudFormation Stack creates AppStream resources within the default VPC."

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsHostnames: True
      Tags:
        - Key: Name
          Value: !Sub ${ApplicationName}-VPC

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Ref ${ApplicationName}-IG

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC


  FleetSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VPC
      GroupDescription: Allow access to AppStream from specific IPs
      SecurityGroupIngress:
        - IpProtocol: -1
          CidrIp: !Ref AllowedIp
      Tags:
        - Key: Name
          Value: !Sub ${ApplicationName}-Fleet

  AppStreamFleet:
    Type: AWS::AppStream::Fleet
    Properties:
      Name: !Sub ${ApplicationName}-fleet
      Description: !Sub This fleet hosting ${ApplicationName} on AppStream
      DisplayName: !Sub A ${ApplicationName} fleet created in CloudFormation
      ImageName: !Ref ImageName
      InstanceType: !Ref InstanceType
      FleetType: !Ref FleetType
      ComputeCapacity:
        DesiredInstances: !Ref DesiredInstances
      VpcConfig:
        SubnetIds: !Split
          - ","
          - !Ref Subnets
        SecurityGroupIds:
          - !Ref FleetSecurityGroup
      MaxUserDurationInSeconds: "57600"
      DisconnectTimeoutInSeconds: "900"
      EnableDefaultInternetAccess: False
    CreationPolicy:
      StartFleet: True

  ScaleTarget:
    Type: 'AWS::ApplicationAutoScaling::ScalableTarget'
    Properties:
      MinCapacity: 
      MaxCapacity: 5
      ResourceId:  !Join
        - ''
        - - 'fleet/'
          - !Ref AppStreamFleet
      RoleARN: >-
        arn:aws:iam::<aws-account-number>:role/service-role/ApplicationAutoScalingForAmazonAppStreamAccess
      ScalableDimension: 'appstream:fleet:DesiredCapacity'
      ServiceNamespace: appstream
    DependsOn:
      - AppStreamFleet

  ScaleInPolicy:
    Type: 'AWS::ApplicationAutoScaling::ScalingPolicy'
    Properties:
      PolicyName: !Join
        - ''
        - - 'ScaleIn-'
          - !Ref AppStreamFleet
      PolicyType: StepScaling
      ScalingTargetId: !Ref ScaleTarget
      StepScalingPolicyConfiguration:
        AdjustmentType: ChangeInCapacity
        Cooldown: 360
        MetricAggregationType: Average
        StepAdjustments:
          - MetricIntervalUpperBound: 0.0
            ScalingAdjustment: -1
    DependsOn:
      - ScaleTarget

  ScaleOutPolicy:
    Type: 'AWS::ApplicationAutoScaling::ScalingPolicy'
    Properties:
      PolicyName:  !Join
        - ''
        - - 'ScaleOut-'
          - !Ref AppStreamFleet
      PolicyType: StepScaling
      ScalingTargetId: !Ref ScaleTarget
      StepScalingPolicyConfiguration:
        AdjustmentType: ChangeInCapacity
        Cooldown: 120
        MetricAggregationType: Average
        StepAdjustments:
          - MetricIntervalLowerBound: 0.0
            ScalingAdjustment: 2
    DependsOn:
      - ScaleTarget

  ScaleInAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties : 
      AlarmActions : 
        - !Ref ScaleInPolicy
      AlarmDescription : "Scale in the fleet when using 25% capacity"
      AlarmName :  !Join
        - ''
        - - 'ScaleInAlarm'
          - !Ref AppStreamFleet
      Dimensions : 
        - Name: Fleet
          Value: !Ref AppStreamFleet
      MetricName : CapacityUtilization
      Namespace : AWS/AppStream
      Period : 120
      EvaluationPeriods : 10      
      Statistic : Average
      Threshold : 25
      ComparisonOperator : LessThanOrEqualToThreshold      
      Unit : Percent
    DependsOn:
      - ScaleInPolicy   

  ScaleOutAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties : 
      AlarmActions : 
        - !Ref ScaleOutPolicy
      AlarmDescription : "Scale out the fleet when using 75% capacity"
      AlarmName :  !Join
        - ''
        - - 'ScaleOutAlarm'
          - !Ref AppStreamFleet
      Dimensions : 
        - Name: Fleet
          Value: !Ref AppStreamFleet
      MetricName : CapacityUtilization
      Namespace : AWS/AppStream
      Period : 60
      EvaluationPeriods : 3      
      Statistic : Average
      Threshold : 75
      ComparisonOperator : GreaterThanOrEqualToThreshold      
      Unit : Percent
    DependsOn:
      - ScaleOutPolicy
      
  AppStreamStack:
    Type: "AWS::AppStream::Stack"
    Properties:
      Name: "DemoStack"
      Description: "This demo stack was created using CloudFormation"
      StorageConnectors:
        - ConnectorType: "HOMEFOLDERS"
          ResourceIdentifier: "TestCloudFormationStackBucket"
          
  AppStreamDemoStackFleetAssociation:
    Type: 'AWS::AppStream::StackFleetAssociation'
    Properties:
      FleetName: !Ref AppStreamFleet
      StackName: !Ref AppStreamStack
    DependsOn:
      - AppStreamFleet
      - AppStreamStack
      
  AppStreamUser:
    Type: "AWS::AppStream::User"
    Properties:
      UserName: "user@email.com"
      FirstName: "John"
      LastName: "Smith"
      AuthenticationType: "USERPOOL"
      
  AppStreamStackUserAssociation:
    Type: "AWS::AppStream::StackUserAssociation"
    Properties:
      UserName: "user@email.com"
      StackName: !Ref AppStreamStack
      SendEmailNotification: False
    DependsOn:
     - AppStreamStack
     - AppStreamUser